defmodule Giulia.AST.PathologicalTest do
  @moduledoc """
  Adversarial AST extraction tests.

  These test Giulia's AST analysis against pathological Elixir code
  that real projects actually contain: macros, nested quotes, protocol
  implementations, generated code, unicode, deeply nested modules,
  dynamic module names, and malformed source.

  The goal is NOT to verify "what the code does" — it's to find
  what the code silently drops or misrepresents.
  """
  use ExUnit.Case, async: true

  alias Giulia.AST.Extraction

  # Helper: parse source with Sourceror (what the indexer actually uses)
  defp parse!(source) do
    case Sourceror.parse_string(source) do
      {:ok, ast} -> ast
      {:error, reason} -> flunk("Failed to parse: #{inspect(reason)}\nSource:\n#{source}")
    end
  end

  # ============================================================================
  # 1. Macro-generated functions — the #1 blind spot
  # ============================================================================

  describe "macro-generated code" do
    test "does NOT see functions generated by `use`" do
      # When you `use GenServer`, init/1, handle_call/3 etc. are injected at compile time.
      # Sourceror only sees the AST before expansion. This test documents the limitation.
      ast = parse!("""
      defmodule MyServer do
        use GenServer

        def start_link(opts), do: GenServer.start_link(__MODULE__, opts)

        @impl true
        def init(state), do: {:ok, state}
      end
      """)

      funcs = Extraction.extract_functions(ast)
      func_names = Enum.map(funcs, & &1.name)

      # We should see the explicitly defined functions
      assert :start_link in func_names
      assert :init in func_names

      # child_spec/1 is injected by `use GenServer` — we should NOT see it
      # because we parse pre-expansion AST. If this assertion fails,
      # something changed in how Sourceror handles `use`.
      refute :child_spec in func_names
    end

    test "functions inside quote blocks are NOT extracted as real functions" do
      # A macro that defines functions via quote — these should NOT appear
      # as top-level functions of the module containing the macro
      ast = parse!("""
      defmodule MyMacro do
        defmacro define_getter(field) do
          quote do
            def unquote(field)(), do: Map.get(@data, unquote(field))
          end
        end
      end
      """)

      funcs = Extraction.extract_functions(ast)
      func_names = Enum.map(funcs, & &1.name)

      # defmacro IS now extracted (Build 115)
      assert :define_getter in func_names
      assert Enum.find(funcs, &(&1.name == :define_getter)).type == :defmacro

      # Functions inside quote blocks should NOT be extracted as real defs
      # (only the defmacro itself should appear, not the quoted def inside)
      refute Enum.any?(funcs, fn f -> f.type == :def end),
        "Found phantom functions from inside quote block: #{inspect(func_names)}"
    end

    test "for-comprehension generating multiple function clauses" do
      ast = parse!("""
      defmodule Generated do
        for {name, value} <- [foo: 1, bar: 2, baz: 3] do
          def unquote(name)(), do: unquote(value)
        end
      end
      """)

      funcs = Extraction.extract_functions(ast)
      # The for+unquote pattern generates functions at compile time.
      # At the AST level, Sourceror sees `unquote(name)` not `:foo`.
      # We should get 0 named functions (they have dynamic names).
      # If we get 3, extraction is somehow expanding the comprehension.
      # If we get 1 with name :unquote, that's also wrong but different.
      assert length(funcs) == 0 or
        Enum.all?(funcs, fn f -> f.name != :foo and f.name != :bar and f.name != :baz end),
        "Extraction should not resolve compile-time generated function names"
    end
  end

  # ============================================================================
  # 2. Nested and unusual module structures
  # ============================================================================

  describe "nested modules" do
    test "extracts both outer and inner modules" do
      ast = parse!("""
      defmodule Outer do
        defmodule Inner do
          def hello, do: :world
        end

        def outer_func, do: :ok
      end
      """)

      modules = Extraction.extract_modules(ast)
      module_names = Enum.map(modules, & &1.name)

      assert "Outer" in module_names
      assert "Outer.Inner" in module_names or "Inner" in module_names
    end

    test "deeply nested modules (3+ levels)" do
      ast = parse!("""
      defmodule A do
        defmodule B do
          defmodule C do
            def deep, do: :ok
          end
        end
      end
      """)

      modules = Extraction.extract_modules(ast)
      assert length(modules) == 3
    end

    test "protocol implementation" do
      ast = parse!("""
      defimpl String.Chars, for: MyStruct do
        def to_string(s), do: inspect(s)
      end
      """)

      # defimpl compiles to defmodule — does extraction see it?
      modules = Extraction.extract_modules(ast)
      funcs = Extraction.extract_functions(ast)

      # Document what actually happens — defimpl may or may not be visible
      # as a defmodule in the pre-expansion AST
      if length(modules) > 0 do
        # Good — it sees the implicit defmodule
        assert hd(modules).name =~ "String.Chars" or hd(modules).name =~ "MyStruct"
      end

      # The to_string function should be found regardless
      func_names = Enum.map(funcs, & &1.name)
      assert :to_string in func_names
    end
  end

  # ============================================================================
  # 3. Edge cases in function definitions
  # ============================================================================

  describe "function definition edge cases" do
    test "function with default arguments" do
      ast = parse!("""
      defmodule Defaults do
        def greet(name, greeting \\\\ "Hello"), do: "\#{greeting}, \#{name}"
      end
      """)

      funcs = Extraction.extract_functions(ast)
      assert length(funcs) >= 1
      greet = Enum.find(funcs, fn f -> f.name == :greet end)
      assert greet != nil
      # Default args: Elixir generates greet/1 AND greet/2,
      # but at AST level we should see arity 2 (the full signature)
      assert greet.arity == 2
    end

    test "multiple function clauses (same name, same arity)" do
      ast = parse!("""
      defmodule MultiClause do
        def handle(:ok), do: :success
        def handle(:error), do: :failure
        def handle(_), do: :unknown
      end
      """)

      funcs = Extraction.extract_functions(ast)
      # uniq_by {name, arity} means we should get exactly 1
      handle_funcs = Enum.filter(funcs, fn f -> f.name == :handle end)
      assert length(handle_funcs) == 1
    end

    test "function with complex guard" do
      ast = parse!("""
      defmodule Guards do
        def process(x) when is_integer(x) and x > 0 and x < 100, do: x * 2
        def process(x) when is_binary(x), do: String.length(x)
      end
      """)

      funcs = Extraction.extract_functions(ast)
      process_funcs = Enum.filter(funcs, fn f -> f.name == :process end)
      assert length(process_funcs) == 1
      assert hd(process_funcs).arity == 1
    end

    test "function with no arguments and no parens" do
      ast = parse!("""
      defmodule NoParens do
        def hello, do: :world
        defp secret, do: :hidden
      end
      """)

      funcs = Extraction.extract_functions(ast)
      assert Enum.any?(funcs, fn f -> f.name == :hello and f.arity == 0 end)
      assert Enum.any?(funcs, fn f -> f.name == :secret and f.arity == 0 end)
    end

    test "defdelegate IS extracted with correct type" do
      ast = parse!("""
      defmodule Delegator do
        defdelegate put(key, value), to: SomeStore
        def local_func, do: :ok
      end
      """)

      funcs = Extraction.extract_functions(ast)
      func_names = Enum.map(funcs, & &1.name)

      assert :local_func in func_names
      assert :put in func_names
      put_func = Enum.find(funcs, &(&1.name == :put))
      assert put_func.type == :defdelegate
      assert put_func.arity == 2
    end
  end

  # ============================================================================
  # 4. Structs edge cases
  # ============================================================================

  describe "struct extraction edge cases" do
    test "struct with enforced keys" do
      ast = parse!("""
      defmodule Strict do
        @enforce_keys [:name, :email]
        defstruct [:name, :email, age: nil, role: :user]
      end
      """)

      structs = Extraction.extract_structs(ast)
      assert length(structs) == 1
      fields = hd(structs).fields
      assert :name in fields
      assert :email in fields
      assert :age in fields
      assert :role in fields
    end

    test "struct defined via module attribute" do
      # Some patterns define struct fields dynamically
      ast = parse!("""
      defmodule Dynamic do
        @fields [:a, :b, :c]
        defstruct @fields
      end
      """)

      structs = Extraction.extract_structs(ast)
      # @fields is a compile-time value — Sourceror sees `defstruct @fields`
      # not `defstruct [:a, :b, :c]`. Extraction should handle this gracefully.
      # It's OK to return empty fields, but it should NOT crash.
      assert is_list(structs)
    end

    test "module with no struct" do
      ast = parse!("""
      defmodule NoStruct do
        def hello, do: :world
      end
      """)

      structs = Extraction.extract_structs(ast)
      assert structs == []
    end
  end

  # ============================================================================
  # 5. Specs and types edge cases
  # ============================================================================

  describe "spec edge cases" do
    test "spec with when clause (type variables)" do
      ast = parse!("""
      defmodule Typed do
        @spec identity(a) :: a when a: term()
        def identity(x), do: x
      end
      """)

      specs = Extraction.extract_specs(ast)
      assert length(specs) >= 1
      spec = hd(specs)
      assert spec.function == :identity
      assert spec.arity == 1
    end

    test "spec with complex union types" do
      ast = parse!("""
      defmodule Complex do
        @spec parse(String.t()) :: {:ok, map()} | {:error, atom()} | :skip
        def parse(s), do: {:ok, %{raw: s}}
      end
      """)

      specs = Extraction.extract_specs(ast)
      assert length(specs) == 1
      assert hd(specs).function == :parse
    end

    test "opaque type" do
      ast = parse!("""
      defmodule Opaque do
        @opaque t :: %__MODULE__{data: term()}
        defstruct [:data]
      end
      """)

      types = Extraction.extract_types(ast)
      assert length(types) >= 1
      assert Enum.any?(types, fn t -> t.name == :t and t.visibility == :opaque end)
    end
  end

  # ============================================================================
  # 6. Malformed / degenerate input
  # ============================================================================

  describe "malformed input" do
    test "empty source" do
      ast = parse!("")
      assert Extraction.extract_modules(ast) == []
      assert Extraction.extract_functions(ast) == []
      assert Extraction.extract_imports(ast) == []
    end

    test "source with only comments" do
      ast = parse!("""
      # This is a comment
      # Another comment
      """)

      assert Extraction.extract_modules(ast) == []
      assert Extraction.extract_functions(ast) == []
    end

    test "source with syntax that parses but has no modules" do
      ast = parse!("""
      x = 1 + 2
      IO.puts("hello")
      """)

      assert Extraction.extract_modules(ast) == []
      assert Extraction.extract_functions(ast) == []
    end

    test "module with empty body" do
      ast = parse!("""
      defmodule Empty do
      end
      """)

      modules = Extraction.extract_modules(ast)
      assert length(modules) == 1
      assert hd(modules).name == "Empty"

      assert Extraction.extract_functions(ast) == []
    end

    test "unparseable source returns errors gracefully" do
      result = Sourceror.parse_string("defmodule Broken do\n  def foo(")
      assert {:error, _} = result
      # Extraction functions should never see unparseable AST because
      # the caller (Processor) guards with parse first.
      # But if they somehow get garbage, they should return [] not crash.
    end

    test "very long module name" do
      parts = Enum.map_join(1..20, ".", fn i -> "Level#{i}" end)
      ast = parse!("defmodule #{parts} do\n  def x, do: :ok\nend")
      modules = Extraction.extract_modules(ast)
      assert length(modules) == 1
      assert hd(modules).name == parts
    end
  end

  # ============================================================================
  # 7. Import/alias edge cases
  # ============================================================================

  describe "import edge cases" do
    test "multi-alias with braces" do
      ast = parse!("""
      defmodule Foo do
        alias MyApp.{Accounts, Repo, Schema}
      end
      """)

      imports = Extraction.extract_imports(ast)
      import_modules = Enum.map(imports, & &1.module)
      assert "MyApp.Accounts" in import_modules
      assert "MyApp.Repo" in import_modules
      assert "MyApp.Schema" in import_modules
    end

    test "use with options" do
      ast = parse!("""
      defmodule MyTest do
        use ExUnit.Case, async: true
      end
      """)

      imports = Extraction.extract_imports(ast)
      assert Enum.any?(imports, fn i -> i.module == "ExUnit.Case" and i.type == :use end)
    end

    test "import with only/except" do
      ast = parse!("""
      defmodule Selective do
        import Enum, only: [map: 2, filter: 2]
        import List, except: [first: 1]
      end
      """)

      imports = Extraction.extract_imports(ast)
      import_modules = Enum.map(imports, & &1.module)
      assert "Enum" in import_modules
      assert "List" in import_modules
    end

    test "require with alias" do
      ast = parse!("""
      defmodule Foo do
        require Logger
        alias Foo.Bar, as: Baz
      end
      """)

      imports = Extraction.extract_imports(ast)
      assert Enum.any?(imports, fn i -> i.module == "Logger" and i.type == :require end)
      assert Enum.any?(imports, fn i -> i.module =~ "Foo.Bar" or i.module =~ "Baz" end)
    end
  end

  # ============================================================================
  # 8. Callbacks and behaviours
  # ============================================================================

  describe "callback extraction" do
    test "behaviour with optional callbacks" do
      ast = parse!("""
      defmodule MyBehaviour do
        @callback required_func(term()) :: :ok
        @callback optional_func(term()) :: :ok
        @optional_callbacks [optional_func: 1]
      end
      """)

      callbacks = Extraction.extract_callbacks(ast)
      assert length(callbacks) == 2

      required = Enum.find(callbacks, fn c -> c.function == :required_func end)
      optional = Enum.find(callbacks, fn c -> c.function == :optional_func end)

      assert required != nil
      assert optional != nil
      refute required.optional
      assert optional.optional
    end

    test "macrocallback is ignored" do
      ast = parse!("""
      defmodule MyBehaviour do
        @macrocallback my_macro(term()) :: Macro.t()
        @callback normal(term()) :: :ok
      end
      """)

      callbacks = Extraction.extract_callbacks(ast)
      # @macrocallback should NOT be extracted (different AST node than @callback)
      func_names = Enum.map(callbacks, & &1.function)
      assert :normal in func_names
      refute :my_macro in func_names
    end
  end

  # ============================================================================
  # 9. Doc extraction edge cases
  # ============================================================================

  describe "doc extraction edge cases" do
    test "doc with heredoc" do
      ast = parse!(~S'''
      defmodule Documented do
        @doc """
        This is a multiline doc.
        It spans several lines.
        """
        def documented_func, do: :ok
      end
      ''')

      docs = Extraction.extract_docs(ast)
      assert length(docs) >= 1
      doc = hd(docs)
      assert doc.function == :documented_func
      assert doc.doc =~ "multiline"
    end

    test "@doc false suppresses doc" do
      ast = parse!("""
      defmodule Hidden do
        @doc false
        def hidden_func, do: :ok
      end
      """)

      docs = Extraction.extract_docs(ast)
      # @doc false is not a string — it should NOT create a doc entry
      refute Enum.any?(docs, fn d -> d.function == :hidden_func end)
    end

    test "doc far from function (>10 lines) is NOT linked" do
      lines = Enum.map_join(1..15, "\n", fn _ -> "  # padding" end)
      ast = parse!("""
      defmodule Spaced do
        @doc "Orphaned doc"
      #{lines}
        def far_away, do: :ok
      end
      """)

      docs = Extraction.extract_docs(ast)
      # The doc is 15+ lines before the function — should not link
      refute Enum.any?(docs, fn d -> d.function == :far_away end)
    end
  end
end
